version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:stable-alpine3.19-perl
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - my_network
    command: ["/bin/sh", "-c", "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

networks:
  my_network:
    driver: bridge
